# Generated by Django 4.0.1 on 2023-03-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_touragencies_imagee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touragencies',
            name='phonenumber',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
