# Generated by Django 4.0.1 on 2023-04-14 10:38

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_touragencies_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to=website.models.get_file_path)),
            ],
        ),
        migrations.AddField(
            model_name='tours',
            name='categoryid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
