# Generated by Django 4.0.1 on 2023-04-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_categoryid_tours_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryid',
            new_name='category_id',
        ),
    ]
