# Generated by Django 4.0.1 on 2023-06-05 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_favorites_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
