# Generated by Django 4.0.1 on 2023-06-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_tours_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('email', models.ForeignKey(default='cookiearu@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
    ]
