# Generated by Django 4.0.1 on 2023-06-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
