# Generated by Django 4.0.1 on 2023-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='name',
            field=models.CharField(default='pohuii', max_length=100),
        ),
    ]
